### PR TITLE
Fix up scripts and dependencies and things

### PR DESCRIPTION
**Pull request by glenjamin**
Here's all the changes I made to get things working again

Using `fps-emit` as a `file:` dependency in `package.json` means you run into https://npm.community/t/npm-install-for-package-with-local-dependency-fails/754 - which supposedly has a fix ready to merge but isn't in a proper npm release yet. The workaround is to delete package-lock before installing, which contributes to some of the churn in this PR.

Here's the output after these changes:

```
> node ./runBenchmarks.js

Running benchmark stockticker
  react-redux version: 5.1.1
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)
  react-redux version: 6.0.0
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)

Results for benchmark stockticker:
┌─────────┬─────────┬───────────┬───────────┬──────────┬───────────────────────────────────────────────────────────────────────────────────────┐
│ Version │ Avg FPS │ Scripting │ Rendering │ Painting │ FPS Values                                                                            │
├─────────┼─────────┼───────────┼───────────┼──────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ 5.1.1   │ 26.57   │ 10864.07  │ 15112.48  │ 2434.29  │ 1,21,22,21,34,22,27,22,21,22,25,24,32,24,23,22,38,28,24,37,33,23,28,27,28,29,30,28,29 │
├─────────┼─────────┼───────────┼───────────┼──────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ 6.0.0   │ 30.50   │ 13624.41  │ 12883.05  │ 1903.10  │ 1,31,35,34,36,33,35,34,32,30,31,30,29,30,29,25,26,27,26,28,29                         │
└─────────┴─────────┴───────────┴───────────┴──────────┴───────────────────────────────────────────────────────────────────────────────────────┘
Running benchmark tree-view
  react-redux version: 5.1.1
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)
  react-redux version: 6.0.0
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)

Results for benchmark tree-view:
┌─────────┬─────────┬───────────┬───────────┬──────────┬──────────────────────────────────────────────────────────────────────────────────────────┐
│ Version │ Avg FPS │ Scripting │ Rendering │ Painting │ FPS Values                                                                               │
├─────────┼─────────┼───────────┼───────────┼──────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ 5.1.1   │ 50.32   │ 8994.28   │ 8124.62   │ 643.88   │ 1,52,49,51,56,42,48,50,49,52,53,42,53,50,54,46,51,49,53,56,49,55,48,52,47,48,53,49,52    │
├─────────┼─────────┼───────────┼───────────┼──────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ 6.0.0   │ 48.97   │ 12805.45  │ 6476.08   │ 470.50   │ 1,52,48,50,56,55,41,45,43,52,50,54,52,42,59,37,52,53,50,45,47,51,48,47,53,52,46,47,52,41 │
└─────────┴─────────┴───────────┴───────────┴──────────┴──────────────────────────────────────────────────────────────────────────────────────────┘
Running benchmark twitter-lite
  react-redux version: 5.1.1
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)
  react-redux version: 6.0.0
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)

Results for benchmark twitter-lite:
┌─────────┬─────────┬───────────┬───────────┬──────────┬────────────────────────────────────────────────────────────────┐
│ Version │ Avg FPS │ Scripting │ Rendering │ Painting │ FPS Values                                                     │
├─────────┼─────────┼───────────┼───────────┼──────────┼────────────────────────────────────────────────────────────────┤
│ 5.1.1   │ 48.94   │ 20864.57  │ 3748.37   │ 383.96   │ 57,59,60,59,60,59,58,59,55,58,54,47,44,41,33,31,28,27          │
├─────────┼─────────┼───────────┼───────────┼──────────┼────────────────────────────────────────────────────────────────┤
│ 6.0.0   │ 38.45   │ 22855.44  │ 2899.73   │ 325.80   │ 56,60,59,57,58,57,55,50,45,40,33,32,30,29,27,24,23,22,24,23,21 │
└─────────┴─────────┴───────────┴───────────┴──────────┴────────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by markerikson** [comment]
Hmm.  I have to say that something looks screwy there, because I've never seen 6.x be faster than 5.x in the `stock-ticker` benchmark...

**Comment by glenjamin** [comment]
Could it be down to changes between 5.0.7 and 5.1.1?

**Comment by markerikson** [comment]
Unlikely, and it's also out of line with the 5.1.1 results you pasted into the RHL issue thread.  Probably just a fluke.

I'll try to look into some of these aspects today.

**Comment by glenjamin** [comment]
I gave it another go for good measure, including 5.0.7 as well this time:

```
Running benchmark stockticker
  react-redux version: 5.0.7
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)
  react-redux version: 5.1.1
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)
  react-redux version: 6.0.0
    Checking max FPS... (30 seconds)
    Running trace...    (30 seconds)

Results for benchmark stockticker:
┌─────────┬─────────┬───────────┬───────────┬──────────┬────────────────────────────────────────────────────────────────────────────────────┐
│ Version │ Avg FPS │ Scripting │ Rendering │ Painting │ FPS Values                                                                         │
├─────────┼─────────┼───────────┼───────────┼──────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 5.0.7   │ 39.62   │ 10707.93  │ 15071.65  │ 2467.91  │ 1,38,41,40,39,41,43,40,39,41,39,40,41,39,38,37,40,42,39,38,41,36                   │
├─────────┼─────────┼───────────┼───────────┼──────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 5.1.1   │ 36.41   │ 10860.75  │ 14994.21  │ 2373.04  │ 1,39,41,42,40,41,43,41,43,41,39,37,39,37,31,28,37,31,27,32,36,30,33,38,31,33,39,34 │
├─────────┼─────────┼───────────┼───────────┼──────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 6.0.0   │ 26.19   │ 14001.29  │ 12394.34  │ 1885.04  │ 1,34,28,34,35,28,31,29,24,30,21,18,11,16,25,30,29,28,23,27,24,25                   │
└─────────┴─────────┴───────────┴───────────┴──────────┴────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by markerikson** [comment]
Awright, NPM was horribly misbehaving for me today, so I got fed up and switched over to use Yarn instead.

I also changed the FPS calculation to use weighted averages based on duration, rather than trivially averaging the raw FPS values.  Should hopefully be somewhat more accurate.

**Comment by markerikson** [comment]
As an example, I just ran a test with 5.0.7, 5.1.1, and 6.0.0, showing `standard (weighted)` FPS values:

```
┌─────────┬───────────────┬─────────────────────────────────────────────────────────────────────────────────┐
│ Version │ Avg FPS       │ FPS Values                                                                      │
├─────────┼───────────────┼─────────────────────────────────────────────────────────────────────────────────┤
│ 5.0.7   │ 33.44 (30.21) │ 1,36,35,34,30,38,36,33,38,36,35,30,31,30,26,27,33,35,36,37,38,35,34,29,30,34    │
├─────────┼───────────────┼─────────────────────────────────────────────────────────────────────────────────┤
│ 5.1.1   │ 34.62 (32.69) │ 1,30,31,40,39,38,35,39,34,38,36,37,36,30,35,36,34,29,33,31,34,36,38,33,34,33,31 │
├─────────┼───────────────┼─────────────────────────────────────────────────────────────────────────────────┤
│ 6.0.0   │ 25.79 (22.11) │ 1,27,26,30,28,25,27,29,25,26,25,27,22,27,26,24,28,27,26,27,23,25,26,24,19       │
└─────────┴───────────────┴─────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by markerikson** [comment]
@glenjamin : thanks for the help here!

**Pull request merged**
